import React from "react";
import Header from "../components/Header/Header";
import Hero from "../components/Hero/Hero";
import About from "../components/About/About";
import Head from "next/head";

import { Lora } from '@next/font/google'
const lora = Lora({ subsets: ['latin'] })

const App = () => {

  return (
    <div className="landing-page">
      <Head>
        <title>SUI Wine Imports</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header links={[{text: "Home", url:"/"}, {text: "Portolio", url:"/portfolio"}]} />
      <Hero fonts={lora} />
      <About />
    </div>
  );
};

export default App;
