import Head from "next/head";
import Image from "next/image";
import { Manrope, Lora } from "@next/font/google";
import styles from "../styles/Home.module.css";
import React from "react";

const manrope = Manrope({ subsets: ["latin"] });
const lora = Lora({ subsets: ["latin"] });

export default function Home() {
  const [score, setScore] = React.useState(0)
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={manrope.className}>
        <h1 className={lora.className}>Title ok? this is a test</h1>

        className={manrope.className}

        </div>
      </main>
    </>
  );
}
